# Generated by Django 5.1.5 on 2025-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('number_pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц (если оставить пустым, то на странице не будет отображаться)')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Страницы (если оставить пустым, то на странице не будет отображаться)')),
                ('classUser', models.IntegerField(blank=True, null=True, verbose_name='Класс')),
                ('lesson', models.IntegerField(blank=True, null=True, verbose_name='Предмет')),
                ('file', models.FileField(blank=True, null=True, upload_to='products/material/', verbose_name='Материал урока(zip архив)')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/img/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/img/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/img/', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/img/', verbose_name='Изображение 4')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
