# Generated by Django 5.1.5 on 2025-02-12 10:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lesson',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Предмет'),
        ),
    ]
