# Generated by Django 5.1.5 on 2025-02-20 21:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Confidentiality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        verbose_name="Текст в конфиденциальности"
                    ),
                ),
            ],
        ),
    ]
