# Generated by Django 5.1.5 on 2025-02-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='Идентификатор заказа')),
                ('amount', models.CharField(max_length=255, verbose_name='Цена (В копейках)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Статус платежа')),
                ('paymentId', models.CharField(blank=True, max_length=255, null=True, verbose_name='paymentId')),
                ('paymentURL', models.CharField(blank=True, max_length=255, null=True, verbose_name='PaymentURL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('products', models.ManyToManyField(related_name='payments', to='product.product', verbose_name='Продукты')),
            ],
        ),
    ]
