# Generated by Django 5.1.5 on 2025-02-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта пользователя'),
        ),
    ]
